apiVersion: v1
kind: Service
metadata:
  name: kuadrant-bind9
spec:
  type: LoadBalancer
  selector:
    app: edge
  ports:
    - protocol: TCP
      name: tcp
      port: 53
      targetPort: 1053
    - protocol: UDP
      name: udp
      port: 53
      targetPort: 1053
