apiVersion: v1
kind: ConfigMap
metadata:
  name: zone
data:
  named.conf: |
    include "/etc/bind/ddns.key";
    options {
      directory "/var/cache/bind";
      listen-on port 1053 { any; };
      allow-query { any; };
    };
    zone "example.com" {
      type master;
      file "/var/lib/bind/zones/example.com";
      allow-transfer {
          key "example.com-key";
      };
      update-policy {
          grant example.com-key zonesub ANY;
      };
    };
  example.com: |
    $TTL 30
    @         IN SOA  example.com. root.example.com. (
                                    16         ; serial
                                    30         ; refresh (30 seconds)
                                    30         ; retry (30 seconds)
                                    30         ; expire (30 seconds)
                                    30         ; minimum (30 seconds)
                                    )
                            NS      ns.example.com.
    ns                      A       127.0.0.1
