version: "2"
linters:
  enable:
    - misspell
  disable:
    - staticcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - internal/external-dns
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - internal/external-dns
