apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dns-operator
    app.kubernetes.io/instance: remote-cluster-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: dns-operator
  name: dns-operator-remote-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dns-operator-remote-cluster-role
subjects:
- kind: ServiceAccount
  name: dns-operator-remote-cluster
  namespace: dns-operator-system
