apiVersion: kuadrant.io/v1alpha1
kind: DNSRecord
metadata:
  name: dnsrecord-simple-inmem-cluster2
spec:
  rootHost: simple.kuadrant.local
  endpoints:
  - dnsName: simple.kuadrant.local
    recordTTL: 60
    recordType: A
    targets:
    - 172.18.200.2
  delegate: true
