apiVersion: kuadrant.io/v1alpha1
kind: DNSRecord
metadata:
  name: dnsrecord-loadbalanced-inmem-cluster3
spec:
  rootHost: loadbalanced.kuadrant.local
  endpoints:
    - dnsName: loadbalanced.kuadrant.local
      recordTTL: 300
      recordType: CNAME
      targets:
        - klb.loadbalanced.kuadrant.local
    - dnsName: klb.loadbalanced.kuadrant.local
      providerSpecific:
        - name: geo-code
          value: US
      recordTTL: 300
      recordType: CNAME
      setIdentifier: US
      targets:
        - us.klb.loadbalanced.kuadrant.local
    - dnsName: us.klb.loadbalanced.kuadrant.local
      providerSpecific:
        - name: weight
          value: "100"
      recordTTL: 60
      recordType: CNAME
      setIdentifier: cluster3-gw1-ns1.klb.loadbalanced.kuadrant.local
      targets:
        - cluster3-gw1-ns1.klb.loadbalanced.kuadrant.local
    - dnsName: cluster3-gw1-ns1.klb.loadbalanced.kuadrant.local
      recordTTL: 60
      recordType: A
      targets:
        - 172.18.200.3
  delegate: true
