apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: remote-cluster-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dns-operator
    app.kubernetes.io/part-of: dns-operator
    app.kubernetes.io/managed-by: kustomize
  name: remote-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: remote-cluster-role
subjects:
- kind: ServiceAccount
  name: remote-cluster
  namespace: system
