apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuadrant-coredns
  namespace: kuadrant-coredns
spec:
  template:
    spec:
      containers:
        - name: coredns
          imagePullPolicy: IfNotPresent
