apiVersion: kuadrant.io/v1alpha1
kind: DNSRecord
metadata:
  name: c1-loadbalanced-dns
  labels:
    'provider': 'kuadrant'
spec:
  providerRef:
    name: dns-provider-credentials-coredns
  rootHost: k.example.com
  endpoints:
    - dnsName: k.example.com
      recordTTL: 300
      recordType: CNAME
      targets:
        - klb.k.example.com
    - dnsName: klb.k.example.com
      providerSpecific:
        - name: geo-code
          value: GEO-NA
      recordTTL: 300
      recordType: CNAME
      setIdentifier: GEO-NA
      targets:
        - geo-na.klb.k.example.com
    - dnsName: geo-na.klb.k.example.com
      providerSpecific:
        - name: weight
          value: '200'
      recordTTL: 60
      recordType: CNAME
      setIdentifier: cluster1.klb.k.example.com
      targets:
        - cluster1.klb.k.example.com
    - dnsName: cluster1.klb.k.example.com
      recordTTL: 60
      recordType: A
      targets:
        - 81.17.23.20
